name: Python CI/CD

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:

  test:
    name: 'Python${{ matrix.python }}@${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
          - windows-latest
        python:
          - "3.10"
          - "3.11"

    steps:

      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest

      - name: Dependencies
        shell: bash -l {0}
        run: |
          mamba install python=${{ matrix.python }} casadi pytest

      - name: Install
        shell: bash  -l {0}
        run: |
          pip install --no-deps -e .[all]

      - name: Test
        shell: bash  -l {0}
        run: |
          pytest
