name: Python CI/CD

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:

  test:
    name: 'Python${{ matrix.python }}@${{ matrix.os }}'
    needs: package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
          - windows-latest
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Download Python packages
        uses: actions/download-artifact@v3
        with:
          path: dist
          name: dist

      - name: Install wheel
        shell: bash
        run: pip install dist/*.whl

      - name: Import the package
        run: python -c "import hippopt"
